par(mfrow = c(2,2))
with(Newdata, plot(datetime, Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)"))
with(Newdata, plot(datetime, Voltage, type = "l", ylab = "Voltage"))
with(Newdata, plot(datetime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
lines(Newdata$datetime, Newdata$Sub_metering_2, type = "l", col = "red")
lines(Newdata$datetime, Newdata$Sub_metering_3, col = "blue")
legend("topright", lty=1, col = c("black", "red", "blue"), cex = 0.7, legend = c("Sub_metering_1", "Sub_metering_2",
                                                                                 "Sub_metering_3"))    
with(Newdata, plot(datetime, Global_reactive_power, type = "l", ylab = "Global_reactive_power"))
dev.copy(png, file="plot4.png", width = 480, height = 480)
dev.off()