data <- read.csv("household_power_consumption.txt", sep = ";")
datetime <- strptime(paste(data$Date, data$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S")
newdata <- cbind(data, datetime)
newdata$Date <- as.Date(newdata$Date, format = "%d/%m/%Y")
newdata$Sub_metering_1 <- as.numeric(as.character(newdata$Sub_metering_1))
newdata$Sub_metering_2 <- as.numeric(as.character(newdata$Sub_metering_2))
newdata$Sub_metering_3 <- as.numeric(as.character(newdata$Sub_metering_3))
Newdata <- newdata[newdata$Date >= "2007-02-01" & newdata$Date <= "2007-02-02",]
with(Newdata, plot(datetime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
lines(Newdata$datetime, Newdata$Sub_metering_2, type = "l", col = "red")
lines(Newdata$datetime, Newdata$Sub_metering_3, col = "blue")
legend("topright", lty=1, col = c("black", "red", "blue"), cex = 0.7, legend = c("Sub_metering_1", "Sub_metering_2",
  "Sub_metering_3"))                                                                    
dev.copy(png, file="plot3.png", width = 480, height = 480)
dev.off()